-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cmpy is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ar_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ai_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    br_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    bi_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of cmpy is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_10001 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8001 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal bi_V_read_1_reg_794 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bi_V_read_1_reg_794_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal bi_V_read_1_reg_794_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal br_V_read_1_reg_800 : STD_LOGIC_VECTOR (15 downto 0);
    signal br_V_read_1_reg_800_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ar_V_read_1_reg_807 : STD_LOGIC_VECTOR (15 downto 0);
    signal ar_V_read_1_reg_807_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_fu_86_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_reg_812 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln790_fu_92_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln790_reg_819 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln790_fu_96_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln790_reg_824 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_3_fu_102_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_3_reg_829 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln790_4_fu_108_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln790_4_reg_836 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum0_V_fu_131_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum0_V_reg_841 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum0_V_reg_841_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal sum1_V_fu_170_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum1_V_reg_846 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum2_V_fu_197_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum2_V_reg_851 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_771_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_22_reg_886 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_778_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_27_reg_892 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln1192_fu_222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1192_reg_897 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1192_2_fu_225_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1192_2_reg_902 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_785_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_4_reg_907 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_4_reg_907_pp0_iter6_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_4_reg_907_pp0_iter7_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Result_s_reg_918 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_918_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_918_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_918_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_fu_235_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln718_reg_924 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_5_fu_238_p2 : STD_LOGIC_VECTOR (32 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of ret_V_5_fu_238_p2 : signal is "no";
    signal ret_V_5_reg_929 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_5_reg_929_pp0_iter6_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_5_reg_929_pp0_iter7_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Result_8_reg_938 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_reg_938_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_reg_938_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_reg_938_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln713_fu_250_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln713_reg_944 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln713_reg_944_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln718_2_fu_254_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln718_2_reg_949 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_4_reg_954 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_reg_954_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_reg_954_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal r_3_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_reg_960 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_reg_965 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_26_fu_323_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_26_reg_970 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_26_reg_970_pp0_iter8_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal carry_4_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_4_reg_976 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_4_reg_976_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_reg_983 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln790_5_fu_357_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln790_5_reg_989 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_30_fu_406_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_30_reg_994 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_30_reg_994_pp0_iter8_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal carry_6_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_6_reg_1000 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_6_reg_1000_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_reg_1007 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln790_6_fu_440_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln790_6_reg_1013 : STD_LOGIC_VECTOR (14 downto 0);
    signal Range1_all_ones_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_reg_1018 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_reg_1023 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1029 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_reg_1034 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_2_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_2_reg_1039 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_16_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_16_reg_1045 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_fu_78_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rhs_V_fu_82_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_fu_78_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln790_fu_96_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln790_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_fu_112_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_fu_124_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal rhs_V_2_fu_141_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_2_fu_138_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_2_fu_144_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln790_2_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_1_fu_150_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp1731_fu_162_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln790_3_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_2_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp1732_fu_190_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_17_fu_287_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_25_fu_278_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln415_fu_319_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_329_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_294_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_2_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_29_fu_361_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln415_2_fu_402_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_fu_412_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_377_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_2_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_451_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_479_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_444_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_472_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_2_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln790_4_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_573_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_fu_549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_2_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_1_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_1_fu_566_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_3_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_2_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_4_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_2_fu_592_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_2_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln790_5_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_2_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln781_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_4_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_679_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_fu_686_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_1_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln781_2_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_4_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_2_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_5_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_6_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_6_fu_737_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_2_fu_744_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_7_fu_693_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_8_fu_751_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_771_ce : STD_LOGIC;
    signal grp_fu_778_ce : STD_LOGIC;
    signal grp_fu_785_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal ar_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ai_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal br_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal bi_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component resonator_dds_mulg8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component resonator_dds_machbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;



begin
    resonator_dds_mulg8j_U73 : component resonator_dds_mulg8j
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 16,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum1_V_reg_846,
        din1 => ar_V_read_1_reg_807_pp0_iter1_reg,
        ce => grp_fu_771_ce,
        dout => grp_fu_771_p2);

    resonator_dds_mulg8j_U74 : component resonator_dds_mulg8j
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 16,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum2_V_reg_851,
        din1 => br_V_read_1_reg_800_pp0_iter1_reg,
        ce => grp_fu_778_ce,
        dout => grp_fu_778_p2);

    resonator_dds_machbi_U75 : component resonator_dds_machbi
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 16,
        din2_WIDTH => 33,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum0_V_reg_841_pp0_iter2_reg,
        din1 => bi_V_read_1_reg_794_pp0_iter2_reg,
        din2 => p_Val2_22_reg_886,
        ce => grp_fu_785_ce,
        dout => grp_fu_785_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Range1_all_ones_2_reg_1034 <= Range1_all_ones_2_fu_556_p2;
                Range1_all_ones_reg_1018 <= Range1_all_ones_fu_460_p2;
                add_ln713_reg_944 <= add_ln713_fu_250_p2;
                add_ln713_reg_944_pp0_iter6_reg <= add_ln713_reg_944;
                ar_V_read_1_reg_807 <= ar_V_read_int_reg;
                ar_V_read_1_reg_807_pp0_iter1_reg <= ar_V_read_1_reg_807;
                bi_V_read_1_reg_794 <= bi_V_read_int_reg;
                bi_V_read_1_reg_794_pp0_iter1_reg <= bi_V_read_1_reg_794;
                bi_V_read_1_reg_794_pp0_iter2_reg <= bi_V_read_1_reg_794_pp0_iter1_reg;
                br_V_read_1_reg_800 <= br_V_read_int_reg;
                br_V_read_1_reg_800_pp0_iter1_reg <= br_V_read_1_reg_800;
                carry_4_reg_976 <= carry_4_fu_343_p2;
                carry_4_reg_976_pp0_iter8_reg <= carry_4_reg_976;
                carry_6_reg_1000 <= carry_6_fu_426_p2;
                carry_6_reg_1000_pp0_iter8_reg <= carry_6_reg_1000;
                empty_16_reg_1045 <= empty_16_fu_637_p2;
                empty_reg_1029 <= empty_fu_543_p2;
                overflow_2_reg_1039 <= overflow_2_fu_615_p2;
                overflow_reg_1023 <= overflow_fu_521_p2;
                p_Result_10_reg_1007 <= p_Val2_30_fu_406_p2(15 downto 15);
                p_Result_7_reg_983 <= p_Val2_26_fu_323_p2(15 downto 15);
                p_Result_8_reg_938 <= ret_V_5_fu_238_p2(32 downto 32);
                p_Result_8_reg_938_pp0_iter6_reg <= p_Result_8_reg_938;
                p_Result_8_reg_938_pp0_iter7_reg <= p_Result_8_reg_938_pp0_iter6_reg;
                p_Result_8_reg_938_pp0_iter8_reg <= p_Result_8_reg_938_pp0_iter7_reg;
                p_Result_s_reg_918 <= grp_fu_785_p3(32 downto 32);
                p_Result_s_reg_918_pp0_iter6_reg <= p_Result_s_reg_918;
                p_Result_s_reg_918_pp0_iter7_reg <= p_Result_s_reg_918_pp0_iter6_reg;
                p_Result_s_reg_918_pp0_iter8_reg <= p_Result_s_reg_918_pp0_iter7_reg;
                p_Val2_22_reg_886 <= grp_fu_771_p2;
                p_Val2_26_reg_970 <= p_Val2_26_fu_323_p2;
                p_Val2_26_reg_970_pp0_iter8_reg <= p_Val2_26_reg_970;
                p_Val2_27_reg_892 <= grp_fu_778_p2;
                p_Val2_30_reg_994 <= p_Val2_30_fu_406_p2;
                p_Val2_30_reg_994_pp0_iter8_reg <= p_Val2_30_reg_994;
                r_3_reg_960 <= r_3_fu_268_p2;
                r_4_reg_965 <= r_4_fu_273_p2;
                ret_V_3_reg_829 <= ret_V_3_fu_102_p2;
                ret_V_4_reg_907 <= grp_fu_785_p3;
                ret_V_4_reg_907_pp0_iter6_reg <= ret_V_4_reg_907;
                ret_V_4_reg_907_pp0_iter7_reg <= ret_V_4_reg_907_pp0_iter6_reg;
                ret_V_5_reg_929 <= ret_V_5_fu_238_p2;
                ret_V_5_reg_929_pp0_iter6_reg <= ret_V_5_reg_929;
                ret_V_5_reg_929_pp0_iter7_reg <= ret_V_5_reg_929_pp0_iter6_reg;
                ret_V_reg_812 <= ret_V_fu_86_p2;
                sub_ln790_reg_824 <= sub_ln790_fu_96_p2;
                sum0_V_reg_841 <= sum0_V_fu_131_p3;
                sum0_V_reg_841_pp0_iter2_reg <= sum0_V_reg_841;
                sum1_V_reg_846 <= sum1_V_fu_170_p3;
                sum2_V_reg_851 <= sum2_V_fu_197_p3;
                tmp_4_reg_954 <= ret_V_5_fu_238_p2(32 downto 31);
                tmp_4_reg_954_pp0_iter6_reg <= tmp_4_reg_954;
                tmp_4_reg_954_pp0_iter7_reg <= tmp_4_reg_954_pp0_iter6_reg;
                trunc_ln1192_2_reg_902 <= trunc_ln1192_2_fu_225_p1;
                trunc_ln1192_reg_897 <= trunc_ln1192_fu_222_p1;
                trunc_ln718_2_reg_949 <= trunc_ln718_2_fu_254_p1;
                trunc_ln718_reg_924 <= trunc_ln718_fu_235_p1;
                trunc_ln790_4_reg_836 <= trunc_ln790_4_fu_108_p1;
                trunc_ln790_5_reg_989 <= trunc_ln790_5_fu_357_p1;
                trunc_ln790_6_reg_1013 <= trunc_ln790_6_fu_440_p1;
                trunc_ln790_reg_819 <= trunc_ln790_fu_92_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                ai_V_read_int_reg <= ai_V_read;
                ar_V_read_int_reg <= ar_V_read;
                bi_V_read_int_reg <= bi_V_read;
                br_V_read_int_reg <= br_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= select_ln340_7_fu_693_p3;
                ap_return_1_int_reg <= select_ln340_8_fu_751_p3;
            end if;
        end if;
    end process;
    Range1_all_ones_2_fu_556_p2 <= "1" when (tmp_4_reg_954_pp0_iter7_reg = ap_const_lv2_3) else "0";
    Range1_all_ones_fu_460_p2 <= "1" when (tmp_2_fu_451_p4 = ap_const_lv2_3) else "0";
    Range1_all_zeros_1_fu_561_p2 <= "1" when (tmp_4_reg_954_pp0_iter7_reg = ap_const_lv2_0) else "0";
    Range1_all_zeros_fu_466_p2 <= "1" when (tmp_2_fu_451_p4 = ap_const_lv2_0) else "0";
    Range2_all_ones_1_fu_549_p3 <= ret_V_5_reg_929_pp0_iter7_reg(32 downto 32);
    Range2_all_ones_fu_444_p3 <= ret_V_4_reg_907_pp0_iter7_reg(32 downto 32);
    add_ln713_fu_250_p2 <= std_logic_vector(unsigned(trunc_ln1192_2_reg_902) + unsigned(trunc_ln1192_reg_897));
    and_ln415_2_fu_396_p2 <= (tmp_27_fu_389_p3 and r_5_fu_384_p2);
    and_ln415_fu_313_p2 <= (tmp_19_fu_306_p3 and r_fu_301_p2);
    and_ln779_1_fu_586_p2 <= (xor_ln779_2_fu_580_p2 and Range2_all_ones_1_fu_549_p3);
    and_ln779_fu_492_p2 <= (xor_ln779_fu_486_p2 and Range2_all_ones_fu_444_p3);
    and_ln781_1_fu_701_p2 <= (carry_6_reg_1000_pp0_iter8_reg and Range1_all_ones_2_reg_1034);
    and_ln781_fu_643_p2 <= (carry_4_reg_976_pp0_iter8_reg and Range1_all_ones_reg_1018);
    and_ln786_2_fu_621_p2 <= (p_Result_10_reg_1007 and deleted_ones_2_fu_592_p3);
    and_ln786_fu_527_p2 <= (p_Result_7_reg_983 and deleted_ones_fu_498_p3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(select_ln340_7_fu_693_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= select_ln340_7_fu_693_p3;
        end if; 
    end process;


    ap_return_1_assign_proc : process(select_ln340_8_fu_751_p3, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= select_ln340_8_fu_751_p3;
        end if; 
    end process;

    carry_4_fu_343_p2 <= (xor_ln416_fu_337_p2 and p_Result_6_fu_294_p3);
    carry_6_fu_426_p2 <= (xor_ln416_2_fu_420_p2 and p_Result_9_fu_377_p3);
    deleted_ones_2_fu_592_p3 <= 
        and_ln779_1_fu_586_p2 when (carry_6_reg_1000(0) = '1') else 
        Range1_all_ones_2_fu_556_p2;
    deleted_ones_fu_498_p3 <= 
        and_ln779_fu_492_p2 when (carry_4_reg_976(0) = '1') else 
        Range1_all_ones_fu_460_p2;
    deleted_zeros_1_fu_566_p3 <= 
        Range1_all_ones_2_fu_556_p2 when (carry_6_reg_1000(0) = '1') else 
        Range1_all_zeros_1_fu_561_p2;
    deleted_zeros_fu_472_p3 <= 
        Range1_all_ones_fu_460_p2 when (carry_4_reg_976(0) = '1') else 
        Range1_all_zeros_fu_466_p2;
    empty_16_fu_637_p2 <= (xor_ln786_2_fu_626_p2 or icmp_ln790_5_fu_632_p2);
    empty_fu_543_p2 <= (xor_ln786_fu_532_p2 or icmp_ln790_4_fu_538_p2);

    grp_fu_771_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_771_ce <= ap_const_logic_1;
        else 
            grp_fu_771_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_778_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_778_ce <= ap_const_logic_1;
        else 
            grp_fu_778_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_785_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_785_ce <= ap_const_logic_1;
        else 
            grp_fu_785_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln790_2_fu_158_p2 <= "1" when (br_V_read_1_reg_800 = sub_ln790_reg_824) else "0";
    icmp_ln790_3_fu_185_p2 <= "1" when (trunc_ln790_4_reg_836 = ap_const_lv16_0) else "0";
    icmp_ln790_4_fu_538_p2 <= "1" when (trunc_ln790_5_reg_989 = ap_const_lv15_0) else "0";
    icmp_ln790_5_fu_632_p2 <= "1" when (trunc_ln790_6_reg_1013 = ap_const_lv15_0) else "0";
    icmp_ln790_fu_119_p2 <= "1" when (trunc_ln790_reg_819 = ap_const_lv16_0) else "0";
        lhs_V_2_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(br_V_read_1_reg_800),17));

    lhs_V_fu_78_p0 <= ar_V_read_int_reg;
        lhs_V_fu_78_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_fu_78_p0),17));

    neg_src_1_fu_150_p3 <= ret_V_2_fu_144_p2(16 downto 16);
    neg_src_2_fu_178_p3 <= ret_V_3_reg_829(16 downto 16);
    neg_src_fu_112_p3 <= ret_V_reg_812(16 downto 16);
    or_ln340_4_fu_674_p2 <= (xor_ln340_fu_668_p2 or overflow_reg_1023);
    or_ln340_5_fu_721_p2 <= (underflow_4_fu_716_p2 or overflow_2_reg_1039);
    or_ln340_6_fu_732_p2 <= (xor_ln340_2_fu_726_p2 or overflow_2_reg_1039);
    or_ln340_fu_663_p2 <= (underflow_fu_658_p2 or overflow_reg_1023);
    or_ln785_2_fu_605_p2 <= (xor_ln785_3_fu_599_p2 or p_Result_10_reg_1007);
    or_ln785_fu_511_p2 <= (xor_ln785_fu_505_p2 or p_Result_7_reg_983);
    overflow_2_fu_615_p2 <= (xor_ln785_4_fu_610_p2 and or_ln785_2_fu_605_p2);
    overflow_fu_521_p2 <= (xor_ln785_2_fu_516_p2 and or_ln785_fu_511_p2);
    p_Result_6_fu_294_p3 <= ret_V_4_reg_907_pp0_iter6_reg(30 downto 30);
    p_Result_9_fu_377_p3 <= ret_V_5_reg_929_pp0_iter6_reg(30 downto 30);
    p_Val2_25_fu_278_p4 <= ret_V_4_reg_907_pp0_iter6_reg(30 downto 15);
    p_Val2_26_fu_323_p2 <= std_logic_vector(unsigned(p_Val2_25_fu_278_p4) + unsigned(zext_ln415_fu_319_p1));
    p_Val2_29_fu_361_p4 <= ret_V_5_reg_929_pp0_iter6_reg(30 downto 15);
    p_Val2_30_fu_406_p2 <= std_logic_vector(unsigned(p_Val2_29_fu_361_p4) + unsigned(zext_ln415_2_fu_402_p1));
    phitmp1731_fu_162_p3 <= 
        ap_const_lv17_10001 when (icmp_ln790_2_fu_158_p2(0) = '1') else 
        ret_V_2_fu_144_p2;
    phitmp1732_fu_190_p3 <= 
        ap_const_lv17_10001 when (icmp_ln790_3_fu_185_p2(0) = '1') else 
        ret_V_3_reg_829;
    phitmp_fu_124_p3 <= 
        ap_const_lv17_10001 when (icmp_ln790_fu_119_p2(0) = '1') else 
        ret_V_reg_812;
    r_3_fu_268_p2 <= "0" when (trunc_ln718_reg_924 = ap_const_lv14_0) else "1";
    r_4_fu_273_p2 <= "0" when (trunc_ln718_2_reg_949 = ap_const_lv14_0) else "1";
    r_5_fu_384_p2 <= (tmp_25_fu_370_p3 or r_4_reg_965);
    r_fu_301_p2 <= (tmp_17_fu_287_p3 or r_3_reg_960);
    ret_V_2_fu_144_p2 <= std_logic_vector(signed(rhs_V_2_fu_141_p1) + signed(lhs_V_2_fu_138_p1));
    ret_V_3_fu_102_p2 <= std_logic_vector(signed(rhs_V_fu_82_p1) - signed(lhs_V_fu_78_p1));
    ret_V_5_fu_238_p2 <= std_logic_vector(signed(p_Val2_22_reg_886) + signed(p_Val2_27_reg_892));
    ret_V_fu_86_p2 <= std_logic_vector(signed(rhs_V_fu_82_p1) + signed(lhs_V_fu_78_p1));
        rhs_V_2_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bi_V_read_1_reg_794),17));

        rhs_V_fu_82_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ai_V_read_int_reg),17));

    select_ln340_6_fu_737_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_5_fu_721_p2(0) = '1') else 
        p_Val2_30_reg_994_pp0_iter8_reg;
    select_ln340_7_fu_693_p3 <= 
        select_ln340_fu_679_p3 when (or_ln340_4_fu_674_p2(0) = '1') else 
        select_ln388_fu_686_p3;
    select_ln340_8_fu_751_p3 <= 
        select_ln340_6_fu_737_p3 when (or_ln340_6_fu_732_p2(0) = '1') else 
        select_ln388_2_fu_744_p3;
    select_ln340_fu_679_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_fu_663_p2(0) = '1') else 
        p_Val2_26_reg_970_pp0_iter8_reg;
    select_ln388_2_fu_744_p3 <= 
        ap_const_lv16_8001 when (underflow_4_fu_716_p2(0) = '1') else 
        p_Val2_30_reg_994_pp0_iter8_reg;
    select_ln388_fu_686_p3 <= 
        ap_const_lv16_8001 when (underflow_fu_658_p2(0) = '1') else 
        p_Val2_26_reg_970_pp0_iter8_reg;
    sub_ln790_fu_96_p1 <= bi_V_read_int_reg;
    sub_ln790_fu_96_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(sub_ln790_fu_96_p1));
    sum0_V_fu_131_p3 <= 
        phitmp_fu_124_p3 when (neg_src_fu_112_p3(0) = '1') else 
        ret_V_reg_812;
    sum1_V_fu_170_p3 <= 
        phitmp1731_fu_162_p3 when (neg_src_1_fu_150_p3(0) = '1') else 
        ret_V_2_fu_144_p2;
    sum2_V_fu_197_p3 <= 
        phitmp1732_fu_190_p3 when (neg_src_2_fu_178_p3(0) = '1') else 
        ret_V_3_reg_829;
    tmp1_fu_711_p2 <= (xor_ln781_2_fu_705_p2 and empty_16_reg_1045);
    tmp_17_fu_287_p3 <= ret_V_4_reg_907_pp0_iter6_reg(15 downto 15);
    tmp_19_fu_306_p3 <= ret_V_4_reg_907_pp0_iter6_reg(14 downto 14);
    tmp_20_fu_329_p3 <= p_Val2_26_fu_323_p2(15 downto 15);
    tmp_23_fu_479_p3 <= ret_V_4_reg_907_pp0_iter7_reg(31 downto 31);
    tmp_25_fu_370_p3 <= ret_V_5_reg_929_pp0_iter6_reg(15 downto 15);
    tmp_27_fu_389_p3 <= add_ln713_reg_944_pp0_iter6_reg(14 downto 14);
    tmp_28_fu_412_p3 <= p_Val2_30_fu_406_p2(15 downto 15);
    tmp_2_fu_451_p4 <= ret_V_4_reg_907_pp0_iter7_reg(32 downto 31);
    tmp_31_fu_573_p3 <= ret_V_5_reg_929_pp0_iter7_reg(31 downto 31);
    tmp_fu_653_p2 <= (xor_ln781_fu_647_p2 and empty_reg_1029);
    trunc_ln1192_2_fu_225_p1 <= grp_fu_778_p2(32 - 1 downto 0);
    trunc_ln1192_fu_222_p1 <= grp_fu_771_p2(32 - 1 downto 0);
    trunc_ln718_2_fu_254_p1 <= ret_V_5_fu_238_p2(14 - 1 downto 0);
    trunc_ln718_fu_235_p1 <= grp_fu_785_p3(14 - 1 downto 0);
    trunc_ln790_4_fu_108_p1 <= ret_V_3_fu_102_p2(16 - 1 downto 0);
    trunc_ln790_5_fu_357_p1 <= p_Val2_26_fu_323_p2(15 - 1 downto 0);
    trunc_ln790_6_fu_440_p1 <= p_Val2_30_fu_406_p2(15 - 1 downto 0);
    trunc_ln790_fu_92_p1 <= ret_V_fu_86_p2(16 - 1 downto 0);
    underflow_4_fu_716_p2 <= (tmp1_fu_711_p2 and p_Result_8_reg_938_pp0_iter8_reg);
    underflow_fu_658_p2 <= (tmp_fu_653_p2 and p_Result_s_reg_918_pp0_iter8_reg);
    xor_ln340_2_fu_726_p2 <= (underflow_4_fu_716_p2 xor ap_const_lv1_1);
    xor_ln340_fu_668_p2 <= (underflow_fu_658_p2 xor ap_const_lv1_1);
    xor_ln416_2_fu_420_p2 <= (tmp_28_fu_412_p3 xor ap_const_lv1_1);
    xor_ln416_fu_337_p2 <= (tmp_20_fu_329_p3 xor ap_const_lv1_1);
    xor_ln779_2_fu_580_p2 <= (tmp_31_fu_573_p3 xor ap_const_lv1_1);
    xor_ln779_fu_486_p2 <= (tmp_23_fu_479_p3 xor ap_const_lv1_1);
    xor_ln781_2_fu_705_p2 <= (ap_const_lv1_1 xor and_ln781_1_fu_701_p2);
    xor_ln781_fu_647_p2 <= (ap_const_lv1_1 xor and_ln781_fu_643_p2);
    xor_ln785_2_fu_516_p2 <= (p_Result_s_reg_918_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln785_3_fu_599_p2 <= (deleted_zeros_1_fu_566_p3 xor ap_const_lv1_1);
    xor_ln785_4_fu_610_p2 <= (p_Result_8_reg_938_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln785_fu_505_p2 <= (deleted_zeros_fu_472_p3 xor ap_const_lv1_1);
    xor_ln786_2_fu_626_p2 <= (ap_const_lv1_1 xor and_ln786_2_fu_621_p2);
    xor_ln786_fu_532_p2 <= (ap_const_lv1_1 xor and_ln786_fu_527_p2);
    zext_ln415_2_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_2_fu_396_p2),16));
    zext_ln415_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_fu_313_p2),16));
end behav;
