-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aphase_to_sincos is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    phases_0_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_1_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_2_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_3_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_4_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_5_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_6_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    phases_7_V_read : IN STD_LOGIC_VECTOR (21 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of aphase_to_sincos is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_phase_to_sincos_fu_82_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_82_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_82_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_82_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_82_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_82_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_82_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call9 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call9 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call9 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call9 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call9 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call9 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call9 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call9 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call9 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call9 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call9 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp23 : BOOLEAN;
    signal grp_phase_to_sincos_fu_92_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_92_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_92_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_92_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_92_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_92_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_92_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call12 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call12 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call12 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call12 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call12 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call12 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call12 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call12 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call12 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call12 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call12 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call12 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call12 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp24 : BOOLEAN;
    signal grp_phase_to_sincos_fu_102_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_102_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_102_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_102_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_102_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_102_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_102_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call15 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call15 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call15 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call15 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call15 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call15 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call15 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call15 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call15 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call15 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call15 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call15 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call15 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call15 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp25 : BOOLEAN;
    signal grp_phase_to_sincos_fu_112_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_112_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_112_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_112_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_112_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_112_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_112_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call18 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call18 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call18 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call18 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call18 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call18 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call18 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call18 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call18 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call18 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call18 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call18 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call18 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call18 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp26 : BOOLEAN;
    signal grp_phase_to_sincos_fu_122_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_122_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_122_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_122_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_122_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_122_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_122_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call21 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call21 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call21 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call21 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call21 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call21 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call21 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call21 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call21 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call21 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call21 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call21 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call21 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call21 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp27 : BOOLEAN;
    signal grp_phase_to_sincos_fu_132_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_132_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_132_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_132_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_132_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_132_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_132_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call24 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call24 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call24 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call24 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call24 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call24 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call24 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call24 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call24 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call24 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call24 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call24 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call24 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call24 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp28 : BOOLEAN;
    signal grp_phase_to_sincos_fu_142_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_142_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_142_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_142_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_142_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_142_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_142_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call27 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call27 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call27 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call27 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call27 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call27 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call27 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call27 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call27 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call27 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call27 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call27 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call27 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call27 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp29 : BOOLEAN;
    signal grp_phase_to_sincos_fu_152_ap_start : STD_LOGIC;
    signal grp_phase_to_sincos_fu_152_ap_done : STD_LOGIC;
    signal grp_phase_to_sincos_fu_152_ap_idle : STD_LOGIC;
    signal grp_phase_to_sincos_fu_152_ap_ready : STD_LOGIC;
    signal grp_phase_to_sincos_fu_152_ap_ce : STD_LOGIC;
    signal grp_phase_to_sincos_fu_152_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_phase_to_sincos_fu_152_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call30 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call30 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call30 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call30 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call30 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call30 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call30 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call30 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call30 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call30 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call30 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call30 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call30 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call30 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp30 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to12 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component phase_to_sincos IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        acc_V : IN STD_LOGIC_VECTOR (21 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_phase_to_sincos_fu_82 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_82_ap_start,
        ap_done => grp_phase_to_sincos_fu_82_ap_done,
        ap_idle => grp_phase_to_sincos_fu_82_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_82_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_82_ap_ce,
        acc_V => phases_0_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_82_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_82_ap_return_1);

    grp_phase_to_sincos_fu_92 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_92_ap_start,
        ap_done => grp_phase_to_sincos_fu_92_ap_done,
        ap_idle => grp_phase_to_sincos_fu_92_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_92_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_92_ap_ce,
        acc_V => phases_1_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_92_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_92_ap_return_1);

    grp_phase_to_sincos_fu_102 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_102_ap_start,
        ap_done => grp_phase_to_sincos_fu_102_ap_done,
        ap_idle => grp_phase_to_sincos_fu_102_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_102_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_102_ap_ce,
        acc_V => phases_2_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_102_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_102_ap_return_1);

    grp_phase_to_sincos_fu_112 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_112_ap_start,
        ap_done => grp_phase_to_sincos_fu_112_ap_done,
        ap_idle => grp_phase_to_sincos_fu_112_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_112_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_112_ap_ce,
        acc_V => phases_3_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_112_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_112_ap_return_1);

    grp_phase_to_sincos_fu_122 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_122_ap_start,
        ap_done => grp_phase_to_sincos_fu_122_ap_done,
        ap_idle => grp_phase_to_sincos_fu_122_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_122_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_122_ap_ce,
        acc_V => phases_4_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_122_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_122_ap_return_1);

    grp_phase_to_sincos_fu_132 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_132_ap_start,
        ap_done => grp_phase_to_sincos_fu_132_ap_done,
        ap_idle => grp_phase_to_sincos_fu_132_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_132_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_132_ap_ce,
        acc_V => phases_5_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_132_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_132_ap_return_1);

    grp_phase_to_sincos_fu_142 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_142_ap_start,
        ap_done => grp_phase_to_sincos_fu_142_ap_done,
        ap_idle => grp_phase_to_sincos_fu_142_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_142_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_142_ap_ce,
        acc_V => phases_6_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_142_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_142_ap_return_1);

    grp_phase_to_sincos_fu_152 : component phase_to_sincos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_phase_to_sincos_fu_152_ap_start,
        ap_done => grp_phase_to_sincos_fu_152_ap_done,
        ap_idle => grp_phase_to_sincos_fu_152_ap_idle,
        ap_ready => grp_phase_to_sincos_fu_152_ap_ready,
        ap_ce => grp_phase_to_sincos_fu_152_ap_ce,
        acc_V => phases_7_V_read,
        ap_return_0 => grp_phase_to_sincos_fu_152_ap_return_0,
        ap_return_1 => grp_phase_to_sincos_fu_152_ap_return_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp23_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp23 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp24_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp24 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp25_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp25 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp26_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp26 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp27_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp27 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp28_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp28 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp29_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp29 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp30_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp30 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call12_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call12 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call15_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call15 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call18_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call18 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call21_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call21 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call24_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call24 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call27_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call27 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call30_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call30 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call9_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call9 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to12_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to12 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to12)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to12 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_phase_to_sincos_fu_82_ap_return_0;
    ap_return_1 <= grp_phase_to_sincos_fu_92_ap_return_0;
    ap_return_10 <= grp_phase_to_sincos_fu_102_ap_return_1;
    ap_return_11 <= grp_phase_to_sincos_fu_112_ap_return_1;
    ap_return_12 <= grp_phase_to_sincos_fu_122_ap_return_1;
    ap_return_13 <= grp_phase_to_sincos_fu_132_ap_return_1;
    ap_return_14 <= grp_phase_to_sincos_fu_142_ap_return_1;
    ap_return_15 <= grp_phase_to_sincos_fu_152_ap_return_1;
    ap_return_2 <= grp_phase_to_sincos_fu_102_ap_return_0;
    ap_return_3 <= grp_phase_to_sincos_fu_112_ap_return_0;
    ap_return_4 <= grp_phase_to_sincos_fu_122_ap_return_0;
    ap_return_5 <= grp_phase_to_sincos_fu_132_ap_return_0;
    ap_return_6 <= grp_phase_to_sincos_fu_142_ap_return_0;
    ap_return_7 <= grp_phase_to_sincos_fu_152_ap_return_0;
    ap_return_8 <= grp_phase_to_sincos_fu_82_ap_return_1;
    ap_return_9 <= grp_phase_to_sincos_fu_92_ap_return_1;

    grp_phase_to_sincos_fu_102_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp25)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp25) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_102_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_102_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_102_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_102_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_102_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_112_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp26)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp26) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_112_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_112_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_112_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_112_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_112_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_122_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp27)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp27) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_122_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_122_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_122_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_122_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_122_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_132_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp28)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp28) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_132_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_132_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_132_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_132_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_132_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_142_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp29)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp29) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_142_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_142_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_142_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_142_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_142_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_152_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp30)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp30) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_152_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_152_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_152_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_152_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_152_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_82_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp23)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp23))) then 
            grp_phase_to_sincos_fu_82_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_82_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_82_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_82_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_82_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_92_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp24)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp24))) then 
            grp_phase_to_sincos_fu_92_ap_ce <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_92_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_phase_to_sincos_fu_92_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_phase_to_sincos_fu_92_ap_start <= ap_const_logic_1;
        else 
            grp_phase_to_sincos_fu_92_ap_start <= ap_const_logic_0;
        end if; 
    end process;

end behav;
