// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dds_ddc_center_phase_sincos_LUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        acc,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [20:0] acc;
output  [51:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [9:0] cos_lut_address0;
reg    cos_lut_ce0;
wire   [16:0] cos_lut_q0;
wire   [9:0] cos_lut_address1;
reg    cos_lut_ce1;
wire   [16:0] cos_lut_q1;
wire   [8:0] fine_lut_address0;
reg    fine_lut_ce0;
wire   [15:0] fine_lut_q0;
wire   [8:0] fine_adr_V_fu_98_p1;
reg   [8:0] fine_adr_V_reg_346;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] fine_adr_V_reg_346_pp0_iter1_reg;
reg   [8:0] fine_adr_V_reg_346_pp0_iter2_reg;
reg   [8:0] fine_adr_V_reg_346_pp0_iter3_reg;
reg   [1:0] msb_V_reg_351;
reg   [1:0] msb_V_reg_351_pp0_iter1_reg;
reg   [1:0] msb_V_reg_351_pp0_iter2_reg;
reg   [1:0] msb_V_reg_351_pp0_iter3_reg;
reg   [1:0] msb_V_reg_351_pp0_iter4_reg;
wire   [0:0] icmp_ln1065_fu_127_p2;
reg   [0:0] icmp_ln1065_reg_366;
reg   [0:0] icmp_ln1065_reg_366_pp0_iter1_reg;
reg   [0:0] icmp_ln1065_reg_366_pp0_iter2_reg;
reg   [0:0] icmp_ln1065_reg_366_pp0_iter3_reg;
reg   [0:0] icmp_ln1065_reg_366_pp0_iter4_reg;
wire   [9:0] sin_adr_V_1_fu_133_p2;
reg   [9:0] sin_adr_V_1_reg_373;
reg   [16:0] r_V_reg_378;
wire   [17:0] zext_ln39_fu_143_p1;
reg   [17:0] zext_ln39_reg_388;
reg   [17:0] zext_ln39_reg_388_pp0_iter3_reg;
reg   [17:0] zext_ln39_reg_388_pp0_iter4_reg;
wire   [17:0] r_V_4_fu_146_p2;
reg   [17:0] r_V_4_reg_394;
reg   [17:0] r_V_4_reg_394_pp0_iter3_reg;
wire   [16:0] trunc_ln946_fu_152_p1;
reg   [16:0] trunc_ln946_reg_399;
reg   [16:0] r_V_2_reg_404;
reg   [16:0] r_V_2_reg_404_pp0_iter3_reg;
wire   [0:0] icmp_ln946_fu_156_p2;
reg   [0:0] icmp_ln946_reg_411;
wire   [17:0] r_V_5_fu_164_p2;
reg   [17:0] r_V_5_reg_416;
reg   [17:0] r_V_5_reg_416_pp0_iter4_reg;
wire   [16:0] trunc_ln946_1_fu_170_p1;
reg   [16:0] trunc_ln946_1_reg_421;
wire   [0:0] icmp_ln946_1_fu_180_p2;
reg   [0:0] icmp_ln946_1_reg_426;
wire   [17:0] select_ln53_1_fu_212_p3;
reg   [17:0] select_ln53_1_reg_431;
wire   [0:0] xor_ln1065_fu_220_p2;
reg   [0:0] xor_ln1065_reg_436;
wire   [17:0] select_ln53_2_fu_242_p3;
reg   [17:0] select_ln53_2_reg_442;
wire   [63:0] zext_ln587_fu_122_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln587_1_fu_139_p1;
wire   [63:0] zext_ln587_2_fu_250_p1;
wire   [9:0] sin_adr_V_fu_112_p4;
wire   [17:0] zext_ln1453_fu_161_p1;
wire   [16:0] cos_lut_word_fu_185_p3;
wire   [0:0] icmp_ln53_fu_195_p2;
wire   [17:0] phitmp2_fu_174_p3;
wire   [0:0] icmp_ln53_1_fu_207_p2;
wire   [17:0] zext_ln42_fu_191_p1;
wire   [17:0] select_ln53_fu_200_p3;
wire   [0:0] and_ln1065_2_fu_225_p2;
wire   [16:0] select_ln1065_2_fu_231_p3;
wire   [17:0] zext_ln53_fu_238_p1;
wire   [0:0] icmp_ln53_2_fu_260_p2;
wire   [0:0] and_ln1065_fu_265_p2;
wire   [17:0] phitmp3_fu_254_p3;
wire   [0:0] and_ln1065_1_fu_277_p2;
wire   [17:0] select_ln1065_fu_270_p3;
wire   [0:0] icmp_ln53_3_fu_290_p2;
wire   [0:0] icmp_ln53_4_fu_295_p2;
wire   [0:0] icmp_ln53_5_fu_300_p2;
wire   [0:0] and_ln1065_4_fu_311_p2;
wire   [0:0] and_ln1065_3_fu_305_p2;
wire   [0:0] and_ln1065_5_fu_316_p2;
wire   [17:0] select_ln1065_3_fu_322_p3;
wire   [17:0] sin_lut_word_fu_329_p3;
wire   [17:0] cos_lut_word_2_fu_282_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

dds_ddc_center_phase_sincos_LUT_cos_lut_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
cos_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cos_lut_address0),
    .ce0(cos_lut_ce0),
    .q0(cos_lut_q0),
    .address1(cos_lut_address1),
    .ce1(cos_lut_ce1),
    .q1(cos_lut_q1)
);

dds_ddc_center_phase_sincos_LUT_fine_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
fine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fine_lut_address0),
    .ce0(fine_lut_ce0),
    .q0(fine_lut_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fine_adr_V_reg_346 <= fine_adr_V_fu_98_p1;
        fine_adr_V_reg_346_pp0_iter1_reg <= fine_adr_V_reg_346;
        icmp_ln1065_reg_366 <= icmp_ln1065_fu_127_p2;
        icmp_ln1065_reg_366_pp0_iter1_reg <= icmp_ln1065_reg_366;
        msb_V_reg_351 <= {{acc[20:19]}};
        msb_V_reg_351_pp0_iter1_reg <= msb_V_reg_351;
        sin_adr_V_1_reg_373 <= sin_adr_V_1_fu_133_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        fine_adr_V_reg_346_pp0_iter2_reg <= fine_adr_V_reg_346_pp0_iter1_reg;
        fine_adr_V_reg_346_pp0_iter3_reg <= fine_adr_V_reg_346_pp0_iter2_reg;
        icmp_ln1065_reg_366_pp0_iter2_reg <= icmp_ln1065_reg_366_pp0_iter1_reg;
        icmp_ln1065_reg_366_pp0_iter3_reg <= icmp_ln1065_reg_366_pp0_iter2_reg;
        icmp_ln1065_reg_366_pp0_iter4_reg <= icmp_ln1065_reg_366_pp0_iter3_reg;
        icmp_ln946_1_reg_426 <= icmp_ln946_1_fu_180_p2;
        icmp_ln946_reg_411 <= icmp_ln946_fu_156_p2;
        msb_V_reg_351_pp0_iter2_reg <= msb_V_reg_351_pp0_iter1_reg;
        msb_V_reg_351_pp0_iter3_reg <= msb_V_reg_351_pp0_iter2_reg;
        msb_V_reg_351_pp0_iter4_reg <= msb_V_reg_351_pp0_iter3_reg;
        r_V_2_reg_404_pp0_iter3_reg <= r_V_2_reg_404;
        r_V_4_reg_394 <= r_V_4_fu_146_p2;
        r_V_4_reg_394_pp0_iter3_reg <= r_V_4_reg_394;
        r_V_5_reg_416 <= r_V_5_fu_164_p2;
        r_V_5_reg_416_pp0_iter4_reg <= r_V_5_reg_416;
        select_ln53_1_reg_431 <= select_ln53_1_fu_212_p3;
        select_ln53_2_reg_442 <= select_ln53_2_fu_242_p3;
        trunc_ln946_1_reg_421 <= trunc_ln946_1_fu_170_p1;
        trunc_ln946_reg_399 <= trunc_ln946_fu_152_p1;
        xor_ln1065_reg_436 <= xor_ln1065_fu_220_p2;
        zext_ln39_reg_388[16 : 0] <= zext_ln39_fu_143_p1[16 : 0];
        zext_ln39_reg_388_pp0_iter3_reg[16 : 0] <= zext_ln39_reg_388[16 : 0];
        zext_ln39_reg_388_pp0_iter4_reg[16 : 0] <= zext_ln39_reg_388_pp0_iter3_reg[16 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_ce))) begin
        r_V_2_reg_404 <= cos_lut_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_V_reg_378 <= cos_lut_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cos_lut_ce0 = 1'b1;
    end else begin
        cos_lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cos_lut_ce1 = 1'b1;
    end else begin
        cos_lut_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_ce))) begin
        fine_lut_ce0 = 1'b1;
    end else begin
        fine_lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln1065_1_fu_277_p2 = (icmp_ln53_2_fu_260_p2 & icmp_ln1065_reg_366_pp0_iter4_reg);

assign and_ln1065_2_fu_225_p2 = (xor_ln1065_fu_220_p2 & icmp_ln53_fu_195_p2);

assign and_ln1065_3_fu_305_p2 = (icmp_ln53_4_fu_295_p2 & icmp_ln53_3_fu_290_p2);

assign and_ln1065_4_fu_311_p2 = (xor_ln1065_reg_436 & icmp_ln53_5_fu_300_p2);

assign and_ln1065_5_fu_316_p2 = (and_ln1065_4_fu_311_p2 & and_ln1065_3_fu_305_p2);

assign and_ln1065_fu_265_p2 = (xor_ln1065_reg_436 & icmp_ln53_2_fu_260_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = {{{fine_lut_q0}, {sin_lut_word_fu_329_p3}}, {cos_lut_word_2_fu_282_p3}};

assign cos_lut_address0 = zext_ln587_1_fu_139_p1;

assign cos_lut_address1 = zext_ln587_fu_122_p1;

assign cos_lut_word_2_fu_282_p3 = ((and_ln1065_1_fu_277_p2[0:0] == 1'b1) ? 18'd0 : select_ln1065_fu_270_p3);

assign cos_lut_word_fu_185_p3 = ((icmp_ln1065_reg_366_pp0_iter3_reg[0:0] == 1'b1) ? 17'd0 : r_V_2_reg_404_pp0_iter3_reg);

assign fine_adr_V_fu_98_p1 = acc[8:0];

assign fine_lut_address0 = zext_ln587_2_fu_250_p1;

assign icmp_ln1065_fu_127_p2 = ((sin_adr_V_fu_112_p4 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_207_p2 = ((msb_V_reg_351_pp0_iter3_reg == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_2_fu_260_p2 = ((msb_V_reg_351_pp0_iter4_reg == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln53_3_fu_290_p2 = ((msb_V_reg_351_pp0_iter4_reg != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_4_fu_295_p2 = ((msb_V_reg_351_pp0_iter4_reg != 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln53_5_fu_300_p2 = ((msb_V_reg_351_pp0_iter4_reg != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_195_p2 = ((msb_V_reg_351_pp0_iter3_reg == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln946_1_fu_180_p2 = ((trunc_ln946_1_reg_421 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln946_fu_156_p2 = ((trunc_ln946_reg_399 == 17'd0) ? 1'b1 : 1'b0);

assign phitmp2_fu_174_p3 = ((icmp_ln946_reg_411[0:0] == 1'b1) ? 18'd131073 : r_V_4_reg_394_pp0_iter3_reg);

assign phitmp3_fu_254_p3 = ((icmp_ln946_1_reg_426[0:0] == 1'b1) ? 18'd131073 : r_V_5_reg_416_pp0_iter4_reg);

assign r_V_4_fu_146_p2 = (18'd0 - zext_ln39_fu_143_p1);

assign r_V_5_fu_164_p2 = (18'd0 - zext_ln1453_fu_161_p1);

assign select_ln1065_2_fu_231_p3 = ((and_ln1065_2_fu_225_p2[0:0] == 1'b1) ? r_V_2_reg_404_pp0_iter3_reg : 17'd0);

assign select_ln1065_3_fu_322_p3 = ((and_ln1065_5_fu_316_p2[0:0] == 1'b1) ? phitmp3_fu_254_p3 : select_ln53_2_reg_442);

assign select_ln1065_fu_270_p3 = ((and_ln1065_fu_265_p2[0:0] == 1'b1) ? phitmp3_fu_254_p3 : select_ln53_1_reg_431);

assign select_ln53_1_fu_212_p3 = ((icmp_ln53_1_fu_207_p2[0:0] == 1'b1) ? zext_ln42_fu_191_p1 : select_ln53_fu_200_p3);

assign select_ln53_2_fu_242_p3 = ((icmp_ln53_1_fu_207_p2[0:0] == 1'b1) ? phitmp2_fu_174_p3 : zext_ln53_fu_238_p1);

assign select_ln53_fu_200_p3 = ((icmp_ln53_fu_195_p2[0:0] == 1'b1) ? zext_ln39_reg_388_pp0_iter3_reg : phitmp2_fu_174_p3);

assign sin_adr_V_1_fu_133_p2 = (10'd0 - sin_adr_V_fu_112_p4);

assign sin_adr_V_fu_112_p4 = {{acc[18:9]}};

assign sin_lut_word_fu_329_p3 = ((icmp_ln53_2_fu_260_p2[0:0] == 1'b1) ? zext_ln39_reg_388_pp0_iter4_reg : select_ln1065_3_fu_322_p3);

assign trunc_ln946_1_fu_170_p1 = r_V_5_fu_164_p2[16:0];

assign trunc_ln946_fu_152_p1 = r_V_4_fu_146_p2[16:0];

assign xor_ln1065_fu_220_p2 = (icmp_ln1065_reg_366_pp0_iter3_reg ^ 1'd1);

assign zext_ln1453_fu_161_p1 = r_V_2_reg_404;

assign zext_ln39_fu_143_p1 = r_V_reg_378;

assign zext_ln42_fu_191_p1 = cos_lut_word_fu_185_p3;

assign zext_ln53_fu_238_p1 = select_ln1065_2_fu_231_p3;

assign zext_ln587_1_fu_139_p1 = sin_adr_V_1_reg_373;

assign zext_ln587_2_fu_250_p1 = fine_adr_V_reg_346_pp0_iter3_reg;

assign zext_ln587_fu_122_p1 = sin_adr_V_fu_112_p4;

always @ (posedge ap_clk) begin
    zext_ln39_reg_388[17] <= 1'b0;
    zext_ln39_reg_388_pp0_iter3_reg[17] <= 1'b0;
    zext_ln39_reg_388_pp0_iter4_reg[17] <= 1'b0;
end

endmodule //dds_ddc_center_phase_sincos_LUT
